version: 2
updates:
- package-ecosystem: cargo
  directory: "/"
  schedule:
    interval: daily
    time: "00:00"
    timezone: Asia/Kolkata
  open-pull-requests-limit: 99
  ignore:
  - dependency-name: vulkano
    versions:
    - 0.20.0
    - 0.21.0
  - dependency-name: vulkano-shaders
    versions:
    - 0.20.0
    - 0.21.0
